name: 'Publish package'

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --no-git-checks